### PR TITLE
micromasters intermediate refactor

### PR DESCRIPTION
**Pull request by abeglova**
As discussed at the meeting yesterday int__micromasters__program_certificates and int__micromasters__users because they don't include all micromasters students and certificate earners. Also mart_components is a bad name

This PR
1) Renames `intermediate/mart_components` as `intermediate/subqueries`
2) Moves int__micromasters__users into subqueries, since not all micromasters learners are included in that table
3) replaces int__micromasters__program_certificates with the content of marts_micromasters__program_certificates

### CODE REVIEW

**Review by rachellougee — APPROVED** [review]

**Comment by Ferdi** [comment]
> int__micromasters__users into subqueries, since not all micromasters learners are included in that table

if these models are incomplete,  do we want to have a special notation, like `__int__micromasters__users`. . Then we say "dont use models starrtign with double underscore"

**Comment by abeglova** [comment]
@Ferdi sorry, the PR description is confusing. The model is now called subqueries__micromasters__users

**Comment by rachellougee** [comment]
One thing to remind you, these renamed models will not be dropped in production, we might need to manually drop the old name https://docs.getdbt.com/faqs/models/removing-deleted-models

**Comment by abeglova** [comment]
@Ferdi Oh, sorry you meant that instead of having "subquery" in the table name i can add __ to the subquery tables.

Yeah! I like that

**Review by rachellougee — APPROVED** [review]

**Pull request merged**
